@startuml
title Модель: запуск новой игры

actor Клиент
participant "Игра" as Игра
participant "ФабрикаУровней" as ФабрикаУровней
participant "Уровень" as Уровень
participant "Схема" as Схема
participant "ИгровоеПоле" as ИгровоеПоле

Клиент -> Игра : начать()
Игра -> Игра : начатьСУровня(1)
Игра -> ФабрикаУровней : создатьУровень(1)
создать Уровень
ФабрикаУровней --> Уровень : new Уровень(...)
Уровень -> Схема : создать(координаты, соединения, стратегии)
создать Схема
Схема --> Уровень : схема
создать ИгровоеПоле
Уровень -> ИгровоеПоле : new ИгровоеПоле(ширина, высота, схема)
ИгровоеПоле -> Схема : привязатьИгровоеПоле(this)
ИгровоеПоле --> Уровень : игровоеПоле
ФабрикаУровней --> Игра : уровень
Игра -> Игра : сброситьСчетчикХодов()
Игра -> Игра : загрузитьУровень(уровень)
Игра -> Уровень : номер()
Игра -> Уровень : схема()
Уровень --> Игра : схема
Игра -> Схема : привязатьИгру(this)
Игра --> Клиент : запущена игра

@enduml
