@startuml
title Модель: запуск новой игры

actor Клиент
participant "Игра" as Игра
participant "ФабрикаУровней" as ФабрикаУровней
participant "Уровень" as Уровень
participant "Схема" as Схема
participant "ИгровоеПоле" as ИгровоеПоле

Клиент -> Игра : начать()
Игра -> Игра : начатьСУровня(1)
Игра -> ФабрикаУровней : создатьУровень(1)
ФабрикаУровней --> Уровень : new Уровень(...)
Уровень -> ИгровоеПоле : new ИгровоеПоле(ширина, высота)
ИгровоеПоле --> Уровень : игровоеПоле
Уровень -> Схема : создать(координаты, соединения, стратегии, игровоеПоле)
Схема --> Уровень : схема
ФабрикаУровней --> Игра : уровень
Игра -> Игра : сброситьСчетчикХодов()
Игра -> Игра : загрузитьУровень(уровень)
Игра -> Уровень : номер()
Игра --> Клиент : запущена игра

@enduml
