@startuml
title Модель: обычное перемещение узла

actor Клиент
participant "Игра" as Игра
participant "Уровень" as Уровень
participant "Схема" as Схема
participant "Узел" as Узел
participant "ИгровоеПоле" as ИгровоеПоле
participant "Ребро" as Ребро

Клиент -> Игра : переместитьУзел(узел, целеваяПозиция)
Игра -> Уровень : схема()
Уровень --> Игра : схема
Игра -> Схема : переместитьУзел(узел, целеваяПозиция)
Схема -> Схема : проверитьПринадлежностьУзлаСхеме(узел)
Схема -> Узел : рассчитатьПозициюПослеХода(целеваяПозиция)
Узел --> Схема : рассчитаннаяПозиция
Схема -> ИгровоеПоле : можноРазместить(рассчитаннаяПозиция)
ИгровоеПоле --> Схема : true
Схема -> Узел : находитсяВ(рассчитаннаяПозиция)
Узел --> Схема : false
Схема -> Узел : переместитьНапрямуюВ(рассчитаннаяПозиция)
Схема -> Схема : обновитьИнцидентныеРебра(узел)
loop инцидентные ребра
    Схема -> Ребро : обновитьГеометрию()
end
Схема -> Схема : обновитьПересечения()
loop пары ребер
    Схема -> Ребро : пересекаетсяС(другоеРебро)
    Ребро --> Схема : результат
end
Схема --> Игра : true
Игра -> Игра : зарегистрироватьХод()
Игра -> Игра : проверитьХод()
Игра -> Игра : уровеньПройден()
Игра -> Уровень : схема()
Уровень --> Игра : схема
Игра -> Схема : естьПересечения()
Схема --> Игра : true
Игра --> Клиент : true

@enduml
