@startuml
title Представление: новая игра из стартового меню

actor Пользователь
participant "ОкноСтартовогоМеню" as ОкноСтартовогоМеню
participant "ЗапускательИгровойСессии" as ЗапускательИгровойСессии
participant "Игра" as Игра
participant "ОкноИгры" as ОкноИгры

Пользователь -> ОкноСтартовогоМеню : нажать "Новая игра"
ОкноСтартовогоМеню -> ЗапускательИгровойСессии : новаяИгра()
создать Игра
ЗапускательИгровойСессии -> Игра : new Игра()
ЗапускательИгровойСессии -> Игра : начать()
Игра --> ЗапускательИгровойСессии : запущена
ЗапускательИгровойСессии --> ОкноСтартовогоМеню : игра
ОкноСтартовогоМеню -> ОкноСтартовогоМеню : открытьИгру(игра)
создать ОкноИгры
ОкноСтартовогоМеню -> ОкноИгры : new ОкноИгры(игра, действиеВозвратаВМеню)
ОкноСтартовогоМеню -> ОкноИгры : показатьОкно()
ОкноСтартовогоМеню -> ОкноСтартовогоМеню : dispose()
ОкноСтартовогоМеню --> Пользователь : игра окно открыто

@enduml
