@startuml
title Представление: выбор уровня из меню

actor Пользователь
participant "ОкноСтартовогоМеню" as ОкноСтартовогоМеню
participant "ЗапускательИгровойСессии" as ЗапускательИгровойСессии
participant "ДиалогВыбораУровня" as ДиалогВыбораУровня
participant "ОкноИгры" as ОкноИгры

Пользователь -> ОкноСтартовогоМеню : нажать "Выбрать уровень"
ОкноСтартовогоМеню -> ЗапускательИгровойСессии : доступныеНомераУровней()
ЗапускательИгровойСессии --> ОкноСтартовогоМеню : номераУровней
создать ДиалогВыбораУровня
ОкноСтартовогоМеню -> ДиалогВыбораУровня : new ДиалогВыбораУровня(this, номераУровней)
ОкноСтартовогоМеню -> ДиалогВыбораУровня : показатьДиалог()
Пользователь -> ДиалогВыбораУровня : нажать уровень кнопка
ДиалогВыбораУровня -> ДиалогВыбораУровня : выбратьУровень(номерУровня)
ДиалогВыбораУровня --> ОкноСтартовогоМеню : выбранныйНомерУровня
ОкноСтартовогоМеню -> ЗапускательИгровойСессии : играНаУровне(выбранныйНомерУровня)
ЗапускательИгровойСессии --> ОкноСтартовогоМеню : игра
создать ОкноИгры
ОкноСтартовогоМеню -> ОкноИгры : new ОкноИгры(игра, действиеВозвратаВМеню)
ОкноСтартовогоМеню -> ОкноИгры : показатьОкно()
ОкноСтартовогоМеню -> ОкноСтартовогоМеню : dispose()

@enduml
