@startuml
title Представление: перетаскивание узла на поле

actor Пользователь
participant "ПанельИгровогоПоля" as ПанельИгровогоПоля
participant "НавигаторИгровогоПоля" as НавигаторИгровогоПоля
participant "Игра" as Игра
participant "ОкноИгры" as ОкноИгры

Пользователь -> ПанельИгровогоПоля : mousePressed(точка)
ПанельИгровогоПоля -> НавигаторИгровогоПоля : выбратьУзел(точка)
НавигаторИгровогоПоля -> НавигаторИгровогоПоля : найтиУзелВЭкраннойТочке(точка)
НавигаторИгровогоПоля --> ПанельИгровогоПоля : выбранныйУзел()
ПанельИгровогоПоля -> ПанельИгровогоПоля : обновитьПоле()

Пользователь -> ПанельИгровогоПоля : mouseDragged(точка)
ПанельИгровогоПоля -> Игра : текущийУровень()
Игра --> ПанельИгровогоПоля : уровень
ПанельИгровогоПоля -> НавигаторИгровогоПоля : предпросмотрХода(выбранныйУзел, точка)
НавигаторИгровогоПоля --> ПанельИгровогоПоля : предпросмотрПозицииВыбранногоУзла
ПанельИгровогоПоля -> ПанельИгровогоПоля : обновитьПоле()

Пользователь -> ПанельИгровогоПоля : mouseReleased()
ПанельИгровогоПоля -> Игра : номерТекущегоУровня()
Игра --> ПанельИгровогоПоля : номерУровняДоХода
ПанельИгровогоПоля -> Игра : максимальныйПройденныйУровень()
Игра --> ПанельИгровогоПоля : максимальныйПройденныйУровеньДоХода
ПанельИгровогоПоля -> Игра : переместитьУзел(выбранныйУзел, предпросмотрПозицииВыбранногоУзла)
Игра --> ПанельИгровогоПоля : результатПеремещения
ПанельИгровогоПоля -> НавигаторИгровогоПоля : очиститьВыбранныйУзел()
ПанельИгровогоПоля -> ОкноИгры : принять(new ПрогрессУровнейДоХода(номерУровняДоХода, максимальныйПройденныйУровеньДоХода))
ОкноИгры -> ОкноИгры : обработатьПрогрессУровнейДоХода(прогрессУровнейДоХода)
ПанельИгровогоПоля -> ПанельИгровогоПоля : обновитьПоле()

@enduml
