@startuml
title Представление: перетаскивание узла на поле

actor Пользователь
participant "ПанельИгровогоПоля" as ПанельИгровогоПоля
participant "НавигаторИгровогоПоля" as НавигаторИгровогоПоля
participant "Игра" as Игра
participant "Уровень" as Уровень
participant "Схема" as Схема
participant "ОкноИгры" as ОкноИгры

Пользователь -> ПанельИгровогоПоля : mousePressed(точка)
ПанельИгровогоПоля -> НавигаторИгровогоПоля : выбратьУзел(точка)
НавигаторИгровогоПоля -> НавигаторИгровогоПоля : найтиУзелВЭкраннойТочке(точка)
НавигаторИгровогоПоля --> ПанельИгровогоПоля : выбранныйУзел()
ПанельИгровогоПоля -> ПанельИгровогоПоля : обновитьПоле()

Пользователь -> ПанельИгровогоПоля : mouseDragged(точка)
ПанельИгровогоПоля -> Игра : текущийУровень()
Игра --> ПанельИгровогоПоля : уровень
ПанельИгровогоПоля -> НавигаторИгровогоПоля : предпросмотрХода(выбранныйУзел, точка)
НавигаторИгровогоПоля --> ПанельИгровогоПоля : предпросмотрПозицииВыбранногоУзла
ПанельИгровогоПоля -> ПанельИгровогоПоля : обновитьПоле()

Пользователь -> ПанельИгровогоПоля : mouseReleased()
ПанельИгровогоПоля -> Игра : текущийУровень()
Игра --> ПанельИгровогоПоля : уровеньДоХода
ПанельИгровогоПоля -> Уровень : схема()
Уровень --> ПанельИгровогоПоля : схема
ПанельИгровогоПоля -> Схема : переместитьУзел(выбранныйУзел, предпросмотрПозицииВыбранногоУзла)
Схема --> ПанельИгровогоПоля : узел перемещен
ПанельИгровогоПоля -> НавигаторИгровогоПоля : очиститьВыбранныйУзел()
ПанельИгровогоПоля -> ОкноИгры : принять(new РезультатХода(предыдущийНомерУровня, предыдущийМаксимальныйПройденныйУровень))
ОкноИгры -> ОкноИгры : обработатьРезультатХода(результат)
ПанельИгровогоПоля -> ПанельИгровогоПоля : обновитьПоле()

@enduml
