@startuml
title Представление: отрисовка игрового поля

participant "ПанельИгровогоПоля" as ПанельИгровогоПоля
participant "ОтрисовщикИгровогоПоля" as ОтрисовщикИгровогоПоля
participant "ОтрисовщикДоски" as ОтрисовщикДоски
participant "Игра" as Игра
participant "ОтрисовщикГрафа" as ОтрисовщикГрафа
participant "ПалитраГрафа" as ПалитраГрафа
participant "ОтрисовщикРебер" as ОтрисовщикРебер
participant "ОтрисовщикУзлов" as ОтрисовщикУзлов

ПанельИгровогоПоля -> ПанельИгровогоПоля : paintComponent(графика)
ПанельИгровогоПоля -> ОтрисовщикИгровогоПоля : отрисоватьПоле(графика, модельИгры, выбранныйУзел, позицияПредпросмотра)
ОтрисовщикИгровогоПоля -> ОтрисовщикИгровогоПоля : создать копияГрафики
ОтрисовщикИгровогоПоля -> ОтрисовщикДоски : отрисовать(копияГрафики, границыОтсечения, параметрыПоля)
ОтрисовщикДоски --> ОтрисовщикИгровогоПоля : доска отрисована
ОтрисовщикИгровогоПоля -> Игра : текущийУровень()
alt текущийУровень отсутствует
    ОтрисовщикИгровогоПоля --> ПанельИгровогоПоля : отрисована только доска
else текущийУровень существует
    ОтрисовщикИгровогоПоля -> ОтрисовщикГрафа : отрисоватьГраф(копияГрафики, модельИгры, выбранныйУзел, позицияПредпросмотра)
    ОтрисовщикГрафа -> ОтрисовщикРебер : отрисоватьРебра(графика, модельИгры, преобразователь, выбранныйУзел, позицияПредпросмотра, палитраГрафа)
    ОтрисовщикРебер -> ПалитраГрафа : цветОбычногоРебра()
    ОтрисовщикРебер -> ПалитраГрафа : цветПересекающегосяРебра()
    ОтрисовщикРебер --> ОтрисовщикГрафа : ребра отрисованы
    ОтрисовщикГрафа -> ОтрисовщикУзлов : отрисоватьУзлы(графика, модельИгры, преобразователь, выбранныйУзел, позицияПредпросмотра, палитраГрафа)
    ОтрисовщикУзлов -> ПалитраГрафа : цветУзла()
    ОтрисовщикУзлов -> ПалитраГрафа : цветВыбранногоУзла()
    ОтрисовщикУзлов --> ОтрисовщикГрафа : узлы отрисованы
    ОтрисовщикГрафа --> ОтрисовщикИгровогоПоля : граф отрисован
end
ОтрисовщикИгровогоПоля --> ПанельИгровогоПоля : поле отрисовано

@enduml
