@startuml
title Точка расширения представления: создание реестра стратегий отрисовки

actor Клиент
participant "РеестрСтратегийОтрисовкиУзлов" as Реестр
participant "СтратегияОбычнойОтрисовкиУзла" as ОбычнаяСтратегия
participant "СтратегияОтрисовкиФиксированногоУзла" as ФиксированнаяСтратегия
participant "СтратегияОтрисовкиГоризонтальногоУзла" as ГоризонтальнаяСтратегия

Клиент -> Реестр : создатьПоУмолчанию()
создать Реестр
Реестр -> ОбычнаяСтратегия : new СтратегияОбычнойОтрисовкиУзла()
Реестр -> Реестр : new РеестрСтратегийОтрисовкиУзлов(стратегияПоУмолчанию)
Реестр -> ОбычнаяСтратегия : new СтратегияОбычнойОтрисовкиУзла()
Реестр -> Реестр : зарегистрировать(СтратегияСвободногоДвижения.class, стратегияПоУмолчанию)
Реестр -> ФиксированнаяСтратегия : new СтратегияОтрисовкиФиксированногоУзла()
Реестр -> Реестр : зарегистрировать(СтратегияФиксированногоДвижения.class, фиксированнаяСтратегия)
Реестр -> ГоризонтальнаяСтратегия : new СтратегияОтрисовкиГоризонтальногоУзла()
Реестр -> Реестр : зарегистрировать(СтратегияГоризонтальногоДвижения.class, горизонтальнаяСтратегия)
Реестр --> Клиент : реестр

@enduml
