@startuml
title Точка расширения представления: отрисовка фиксированного узла

participant "ОтрисовщикУзлов" as ОтрисовщикУзлов
participant "РеестрСтратегийОтрисовкиУзлов" as Реестр
participant "Узел" as Узел
participant "СтратегияОтрисовкиФиксированногоУзла" as ФиксированнаяСтратегия
participant "СтратегияОбычнойОтрисовкиУзла" as ОбычнаяСтратегия

ОтрисовщикУзлов -> Реестр : выбратьСтратегию(узел)
Реестр -> Узел : получитьСтратегиюДвижения()
Узел --> Реестр : СтратегияФиксированногоДвижения
Реестр --> ОтрисовщикУзлов : СтратегияОтрисовкиФиксированногоУзла
ОтрисовщикУзлов -> ФиксированнаяСтратегия : отрисовать(графика, центр, радиус, цвет, выбран)
ФиксированнаяСтратегия -> ОбычнаяСтратегия : отрисовать(графика, центр, радиус, цвет, выбран)
ОбычнаяСтратегия --> ФиксированнаяСтратегия : базовый узел отрисован
ФиксированнаяСтратегия -> ФиксированнаяСтратегия : отрисовать замок маркер
ФиксированнаяСтратегия --> ОтрисовщикУзлов : фиксированный узел отрисован

@enduml
